version: '2'
services:
  web:
    build: ./web
    ports:
      - "80:8888"
    links:
      - database:db_link
    depends_on:
      - database
  database:
    build: ./database
    ports:
      - "5432:5432"